# NumPy

NumPy oferece sequências de elementos que são mais eficientes que sequências padrões em Python.

In [1]:
import sys # Permite iteragir com o SO
import numpy as np
print(sys.version)
np.__version__

3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]


'1.14.3'

In [2]:
# Criando uma array NumPy
array1 = np.arange(15)

In [3]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# Help
?array1

In [4]:
array1.mean()

7.0

In [5]:
array1.sum()

105

In [6]:
array1.min()

0

In [7]:
array1.max()

14

In [8]:
# Desvio padrão
array1.std()

4.320493798938574

### Utilizando List Comprehension em Arrays NumPy

In [9]:
[x * x for x in array1]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

In [10]:
[x * x for x in array1 if x % 2 == 0]

[0, 4, 16, 36, 64, 100, 144, 196]

### Utilizando Função Lambda em Arrays NumPy

In [11]:
list(filter(lambda x: x % 2 == 0, array1))

[0, 2, 4, 6, 8, 10, 12, 14]

In [12]:
# Atenção com a notação (o NumPy permite) aplica a função ao array
array1 % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True])

In [13]:
# Podemos utilizar notação de indice - retornamos os valores apenas os verdadeiros
array1[array1 % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

### Avaliando a Performance

In [14]:
# Performance usando List Comprehension (mas o array1 é NumPy)
%timeit [x for x in array1 if x % 2 == 0]

5.21 µs ± 46.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [15]:
# Performance usando NumPy
%timeit array1[array1 % 2 == 0]

1.87 µs ± 4.23 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Usando operadore logicos

In [16]:
array1 > 8

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True])

In [17]:
array1[array1 > 8]

array([ 9, 10, 11, 12, 13, 14])

In [18]:
# operador logico and
(array1 > 9) & (array1 < 12)

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True, False, False, False])

In [19]:
# operador logico or
(array1 > 13) | (array1 < 12)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True])

In [20]:
array1[(array1 > 13) | (array1 < 12)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 14])

In [21]:
# Criando um array NumPy com List Comprehension
array2 = np.array([x ** 3 for x in range(15)])

In [22]:
array2

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744])

In [23]:
array2 = np.array([True for x in range(15)])

In [24]:
array2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [25]:
# Usando um array como indice para outro array
array1[array2]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])